# Generated by Django 5.1.1 on 2024-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Last Name'),
        ),
    ]
